apiVersion: apps/v1
kind: Deployment
metadata:
  name: suning-api-backing-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: suning-api
      channel: backing
  template:
    metadata:
      labels:
        app: suning-api
        channel: backing
    spec:
      containers:
      - name: suning-api
        image: gayson/spring-docker-suning-api:0.1
        ports:
        - containerPort: 8080
