apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
      channel: stable
  template:
    metadata:
      labels:
        app: gateway
        channel: stable
    spec:
      containers:
      - name: gateway
        image: gayson/spring-docker-gateway:0.2
        ports:
        - containerPort: 80
