apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-backing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      channel: backing
  template:
    metadata:
      labels:
        app: gateway
        channel: backing
    spec:
      containers:
      - name: gateway
        image: gayson/spring-docker-gateway:0.2
        ports:
        - containerPort: 8080
