apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31658
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 104.199.200.229
