apiVersion: v1
kind: Service
metadata:
  labels:
    app: jd-api
  name: jd-api-service
  namespace: default
spec:
  selector:
    app: jd-api
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
