apiVersion: apps/v1
kind: Deployment
metadata:
  name: jd-api-backing-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jd-api
      channel: backing
  template:
    metadata:
      labels:
        app: jd-api
        channel: backing
    spec:
      containers:
      - name: jd-api
        image: gayson/spring-docker-jd-api:0.1
        ports:
        - containerPort: 8080
